# Generated by Django 2.2.6 on 2019-10-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excp',
            old_name='date_upload',
            new_name='Date',
        ),
        migrations.RemoveField(
            model_name='excp',
            name='text',
        ),
        migrations.AddField(
            model_name='excp',
            name='AppID',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='excp',
            name='ApplicationName',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='excp',
            name='ClientID',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='excp',
            name='ComputerName',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='excp',
            name='ConnectID',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='excp',
            name='Context',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='excp',
            name='DateUpload',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='excp',
            name='Description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='excp',
            name='Exception',
            field=models.CharField(default='', max_length=36),
        ),
        migrations.AddField(
            model_name='excp',
            name='Level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='excp',
            name='Name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='excp',
            name='OSThread',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='excp',
            name='Process',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='excp',
            name='ProcessName',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='excp',
            name='SessionID',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='excp',
            name='User',
            field=models.CharField(default='', max_length=200),
        ),
    ]
